local transport = require and require("railnet.lib.transport") or dofile("/railnet/lib/transport.lua")
transport.init()
local P = {}
local STATE = { depots = {}, trains = {}, selected_depot = nil, selected_train_idx = 1, btns = {} }
local function rjson(p) if not fs.exists(p) then return nil end local h=fs.open(p,"r"); local s=h.readAll(); h.close(); local ok,j=pcall(textutils.unserializeJSON,s); if ok then return j end end
local DEFAULT_COLORS = { status = { idle={fg=colors.lime,bg=colors.black}, dispatch={fg=colors.yellow,bg=colors.black}, service={fg=colors.red,bg=colors.black}, parked={fg=colors.gray,bg=colors.black}, error={fg=colors.white,bg=colors.red}, unknown={fg=colors.white,bg=colors.black} },
  buttons = { dispatch={fg=colors.white,bg=colors.orange}, park={fg=colors.white,bg=colors.gray}, service={fg=colors.white,bg=colors.red}, idle={fg=colors.black,bg=colors.lime}, back={fg=colors.white,bg=colors.blue} },
  header={fg=colors.white,bg=colors.black}, title={fg=colors.white,bg=colors.black}, label={fg=colors.yellow,bg=colors.black} }
local CFG_COLORS = rjson("/railnet/etc/colors.json") or {}
local function get_color(section,key) local sec=(CFG_COLORS[section] or {})[key] or DEFAULT_COLORS[section][key]; return (sec and sec.fg) or colors.white, (sec and sec.bg) or colors.black end
transport.subscribe("depot/hello", function(ev) if not ev or not ev.depot_id then return end local d=STATE.depots[ev.depot_id] or { id=ev.depot_id, name=ev.name or ev.depot_id, cap=ev.capacity or 0, trains={} } d.name=ev.name or d.name; d.cap=ev.capacity or d.cap; STATE.depots[ev.depot_id]=d; if not STATE.selected_depot then STATE.selected_depot = d.id end end)
transport.subscribe("depot/train_register", function(ev) if not ev or not ev.depot_id or not ev.train_id then return end STATE.trains[ev.train_id] = { id=ev.train_id, type=ev.type or "cargo", depot_id=ev.depot_id, status="idle" } end)
transport.subscribe("depot/train_status", function(ev) if not ev or not ev.train_id then return end local t = STATE.trains[ev.train_id]; if not t then return end t.status = ev.status or t.status end)
transport.subscribe("depot/train_idle", function(ev) if not ev or not ev.train_id then return end local t = STATE.trains[ev.train_id]; if not t then return end t.status = "idle" end)
transport.subscribe("depot/train_dispatched", function(ev) if not ev or not ev.train_id then return end local t = STATE.trains[ev.train_id]; if t then t.status = "dispatch" end end)
local function list_trains(depot_id) local lst = {}; for _,t in pairs(STATE.trains) do if t.depot_id==depot_id then table.insert(lst, t) end end table.sort(lst, function(a,b) return (a.id<b.id) end); return lst end
local function draw_header() local fg,bg = get_color("header","title"); term.setBackgroundColor(bg); term.setTextColor(fg); term.clear(); term.setCursorPos(2,1); term.write("Depot – ←/→ Depot  ↑/↓ Zug  [V]ersand  [P]arken  [S]ervice  [I]dle  [Q]uit") end
local function draw_depots(x,y) local lfg,lbg = get_color("label","label"); term.setCursorPos(x,y); term.setTextColor(lfg); term.setBackgroundColor(lbg); term.write("Depots:"); term.setTextColor(colors.white); term.setBackgroundColor(colors.black); y=y+1
  for id,d in pairs(STATE.depots) do term.setCursorPos(x,y); local sel=(STATE.selected_depot==id) and ">" or " "; local free,total=0,0; for _,t in pairs(STATE.trains) do if t.depot_id==id then total=total+1; if t.status=="idle" then free=free+1 end end; term.write(string.format("%s %s  cap:%d  idle:%d/%d", sel, d.name or id, d.cap or 0, free, total)); y=y+1 end end
local function colors_for_status(st) st=st or "unknown"; local fg,bg = get_color("status", st); return fg or colors.white, bg or colors.black end
local function btn(x,y,label,key,style) local w = #label + 2; term.setCursorPos(x,y); term.setBackgroundColor(style.bg or colors.blue); term.setTextColor(style.fg or colors.white); term.write(" "..label.." "); P._btns = P._btns or {}; P._btns[#P._btns+1] = { x=x, y=y, w=w, h=1, key=key }; term.setBackgroundColor(colors.black); term.setTextColor(colors.white); return x + w + 1 end
local function draw_trains(x,y) local did = STATE.selected_depot; if not did then return end local lst = list_trains(did); local lfg,lbg = get_color("label","label"); term.setCursorPos(x,y); term.setTextColor(lfg); term.setBackgroundColor(lbg); term.write("Züge in "..did..":"); term.setTextColor(colors.white); term.setBackgroundColor(colors.black); y=y+1
  local function badge_colors(st) local sec=(CFG_COLORS.badges and CFG_COLORS.badges[st]); if sec and sec.fg and sec.bg then return sec.fg, sec.bg end return colors_for_status(st) end
  for i,t in ipairs(lst) do local sel = (i == (STATE.selected_train_idx or 1)) and ">" or " "; local fg,bg = colors_for_status(t.status); term.setCursorPos(x,y); term.setBackgroundColor(bg); term.setTextColor(fg); local base = string.format("%s %s  %-5s", sel, t.id, t.type or "-"); term.clearLine(); term.write(base); local bfg, bbg = badge_colors(t.status or "unknown"); term.setTextColor(bfg); term.setBackgroundColor(bbg); term.write(" ["..(t.status or "?").."] "); term.setBackgroundColor(colors.black); term.setTextColor(colors.white); y=y+1; if y>18 then break end end end
local function draw_buttons() local _,h = term.getSize(); local y = h - 1; local x = 2; local sf = DEFAULT_COLORS.buttons; P._btns = {}; x = btn(x,y,"Dispatch","v", (sf.dispatch)); x = btn(x,y,"Park","p", (sf.park)); x = btn(x,y,"Service","s", (sf.service)); x = btn(x,y,"Idle","i", (sf.idle)); x = btn(x,y,"Back","q", (sf.back)) end
local function redraw() draw_header(); draw_depots(2,3); draw_trains(2,9); draw_buttons() end
local function select_next_depot(dir) local ids = {}; for id,_ in pairs(STATE.depots) do table.insert(ids, id) end; table.sort(ids); if #ids==0 then return end; local idx = 1; for i,v in ipairs(ids) do if v==STATE.selected_depot then idx=i; break end end; idx = idx + (dir>0 and 1 or -1); if idx<1 then idx=#ids end; if idx>#ids then idx=1 end; STATE.selected_depot = ids[idx]; STATE.selected_train_idx = 1 end
local function list_trains_sorted() return (function(did) local lst = {}; for _,t in pairs(STATE.trains) do if t.depot_id==did then table.insert(lst, t) end end table.sort(lst,function(a,b) return a.id<b.id end); return lst end)(STATE.selected_depot or "") end
local function current_train() local lst = list_trains_sorted(); return lst[STATE.selected_train_idx or 1] end
local function do_dispatch() local t=current_train(); if not t then return end transport.publish("depot/dispatch", { depot_id=t.depot_id, train_id=t.id }) end
local function do_park()     local t=current_train(); if not t then return end transport.publish("depot/park", { depot_id=t.depot_id, train_id=t.id }) end
local function do_service()  local t=current_train(); if not t then return end transport.publish("service/request", { train_id=t.id, reason="manual" }) end
local function do_idle()     local t=current_train(); if not t then return end transport.publish("depot/train_idle", { depot_id=t.depot_id, train_id=t.id }) end
local function handle_key(k) if k==keys.q then return "quit" elseif k==keys.left then select_next_depot(-1) elseif k==keys.right then select_next_depot(1) elseif k==keys.up then STATE.selected_train_idx = math.max(1, (STATE.selected_train_idx or 1) - 1) elseif k==keys.down then STATE.selected_train_idx = (STATE.selected_train_idx or 1) + 1 elseif k==keys.v then do_dispatch() elseif k==keys.p then do_park() elseif k==keys.s then do_service() elseif k==keys.i then do_idle() end end
local function hit(x,y, bx,by,bw,bh) return x>=bx and x<bx+bw and y>=by and y<by+bh end
local function handle_touch(x,y) for _,b in ipairs(P._btns or {}) do if hit(x,y,b.x,b.y,b.w,b.h) then local map = { v=keys.v, p=keys.p, s=keys.s, i=keys.i, q=keys.q }; local k = map[b.key]; if k then return handle_key(k) end end end end
function P.render(t) redraw() end
function P.loop() redraw(); while true do local e,a,b,c = os.pullEvent(); if e=="key" then local ret = handle_key(a); if ret=="quit" then break end; redraw() elseif e=="monitor_touch" or e=="mouse_click" then local ret = handle_touch(b,c); if ret=="quit" then break end; redraw() elseif e=="modem_message" then redraw() end end end
return P
